### ISSUE TITLE
Count running and stopped for each backend

### ISSUE THREAD

**Issue by julbrs** [wiiisdom/ec2-leaser#9]
I want to have the number of running and stopped vm for each backend on the backend-name filed in bottom right: 
![image](https://user-images.githubusercontent.com/4988590/57480256-38b68c00-726d-11e9-95d1-3b18e6d57b6c.png)
THANKS !

**Comment by bobman38** [comment]
Partially done in commit 0b87a317f59b6d6a13a5a8031223f8fe80062400

**Comment by julbrs** [comment]
no more backend support in ec2-leaser, let's close this ticket!
